AWSTemplateFormatVersion: '2010-09-09'
Description: "Network Redux CloudFormation - Redux Operations Security Groups"


Parameters:

  EnvironmentName:
    Description: 'Redux Operations Security Groups - US-EAST'
    Type: String
    Default: 'Network Redux CloudFormation - Redux Operations Security Groups - US-EAST'

Resources:

  InstanceSecurityGroupDNS:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Security Group for Public DNS access"
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: "53"
          ToPort: "53"
          CidrIp: "0.0.0.0/0"
        - IpProtocol: "udp"
          FromPort: "53"
          ToPort: "53"
          CidrIp: "0.0.0.0/0"
      Tags:
        - Key: Name
          Value: SG_OPS_PUBLIC_TO_DNS_SERVERS_DNS

  InstanceSecurityGroupCPANEL:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Security Group for CPanel Management access"
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: "2087"
          ToPort: "2087"
          CidrIp: "61.12.37.114/32"
        - IpProtocol: "tcp"
          FromPort: "2086"
          ToPort: "2086"
          CidrIp: "61.12.37.114/32"
      Tags:
        - Key: Name
          Value: SG_OPS_PUBLIC_TO_CPANEL_SERVERS_WHM
